cover:
- platform: time_based
  name: "${node_name} Cover 01"
  device_class: shutter
  id: cover_01
  open_action:
    - switch.turn_off: cover_close_01
    - switch.turn_on: cover_open_01
  open_duration: 60s
  close_action:
    - switch.turn_off: cover_open_01
    - switch.turn_on: cover_close_01
  close_duration: 60s
  stop_action:
    - switch.turn_off: cover_open_01
    - switch.turn_off: cover_close_01
  # tilt_action:
  #   - cover.close: this cover
  #   - delay: 2s
  #   - switch.turn_on: open_cover_switch
  #   - lambda: |- wyliczenie czasu z zadanej pozycji
  #   - delay: X
  #   - switch.turn_off: open_cover_switch

- platform: time_based
  name: "${node_name} Cover 02"
  device_class: shutter
  id: cover_02
  open_action:
    - switch.turn_off: cover_close_02
    - switch.turn_on: cover_open_02
  open_duration: 60s
  close_action:
    - switch.turn_off: cover_open_02
    - switch.turn_on: cover_close_02
  close_duration: 60s
  stop_action:
    - switch.turn_off: cover_open_02
    - switch.turn_off: cover_close_02

- platform: time_based
  name: "${node_name} Cover 03"
  device_class: shutter
  id: cover_03
  open_action:
    - switch.turn_off: cover_close_03
    - switch.turn_on: cover_open_03
  open_duration: 60s
  close_action:
    - switch.turn_off: cover_open_03
    - switch.turn_on: cover_close_03
  close_duration: 60s
  stop_action:
    - switch.turn_off: cover_open_03
    - switch.turn_off: cover_close_03


