dallas:
- pin: GPIO32
  update_interval: 10s
  
sensor:
- platform: dallas
  address:  0xc33ce1e381796328
  name: "Temp kuchnia"
  
- platform: dallas
  address: 0x803ce1e381134028
  name: "Temp garaż"
#logger:
#  level: VERBOSE

# sensor:
#   - platform: dallas
#     address: 0x283c01d607d4df28
#     name: "Dallas Sensor 1"
#
#   - platform: dallas
#     address: 0xdfe67a061e64ff28
#     name: "Dallas Sensor 2"
#
#   - platform: dallas
#     address: 0xa7a89f071e64ff28
#     name: "Dallas Sensor 3"
