one_wire:
  - platform: gpio
    pin: GPIO32
  
sensor:
#- platform: dallas
#  address:  0xc33ce1e381796328
#  name: "Temp kuchnia"

  - platform: dallas_temp
    address: 0x126f6e7c1f64ff28
    name: "GA_temp"
    update_interval: 30s

  - platform: dallas_temp
    address: 0x9666617c1f64ff28
    name: "PD_temp"
    update_interval: 30s

  - platform: dallas_temp
    address: 0x9e21947d1f64ff28
    name: "P3_temp"
    update_interval: 30s
        
  - platform: dallas_temp
    address: 0x73c3df7d1f64ff28
    name: "P2_temp"
    update_interval: 30s
# sensor:
#   - platform: dallas
#     address: 0x283c01d607d4df28
#     name: "Dallas Sensor 1"
#
#   - platform: dallas
#     address: 0xdfe67a061e64ff28
#     name: "Dallas Sensor 2"
#
#   - platform: dallas
#     address: 0xa7a89f071e64ff28
#     name: "Dallas Sensor 3"
#[21:11:30][D][dallas.sensor:082]:   Found sensors:
#[21:11:30][D][dallas.sensor:084]:     0x126f6e7c1f64ff28
#[21:11:30][D][dallas.sensor:084]:     0x9666617c1f64ff28
#[21:11:30][D][dallas.sensor:084]:     0x9e21947d1f64ff28

                                                          #0x126f6e7c1f64ff28
#[11:09:39][D][dallas.sensor:084]:     0x9666617c1f64ff28
#[11:09:39][D][dallas.sensor:084]:     0x9e21947d1f64ff28
#[11:09:39][D][dallas.sensor:084]:     0x73c3df7d1f64ff28

