uart:
  id: mod_bus
  rx_pin: GPIO3
  tx_pin: GPIO1
  baud_rate: 9600
  parity: NONE
  stop_bits: 1
  debug:

modbus:
  uart_id: mod_bus
  id: modbusid
  send_wait_time: 500ms

modbus_controller:
- id: ch8_1st
  address: 0x3
  modbus_id: modbusid
  update_interval: 10s

switch:
- platform: modbus_controller
  name: 'AA_custom_off'
  custom_command: [0x20, 0x05, 0x00, 0x00, 0x00, 0x00]    

- platform: modbus_controller
  name: 'AA_custom_on'
  custom_command: [0x20, 0x05, 0x00, 0x00, 0xFF, 0x00]
  
